### ISSUE TITLE
Reduce/isolate Ignition's dependency on ethers

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat-ignition#10]
The way the core of Ignition is implemented right now depends a lot on ethers, even for interfaces. This might not be a good idea long-term, so we should either reduce and/or isolate these dependencies.

**Comment by kanej** [comment]
I think this is still true.

I have no problem with ethers being leveraged in **ignition.core** but it should be encapsulated. We should not be exposing its types in the user facing api for instance.

We should do a code review and identify those locations and close them off.

**Comment by kanej** [comment]
@fvictorio is there any problem with a plugin depending on ethers or is there best practice around that?

**Comment by fvictorio** [comment]
I don't think so. The only thing that comes to mind is using a version range as wide as possible, so npm can dedup it (since users probably already depend on ethers directly or indirectly). But that's just a nice to have, not super important.

To be honest, I think I would just close this issue. We are not going to stabilize ignition core's API any time soon and, when we do, any public interface tied to ethers is going to be a super obvious mistake that we can fix. So having an explicit issue about this is probably unnecessary. Your call, of course.
