### ISSUE TITLE
UI: add `chalk` to output of `VerboseEventHandler` for increased readability

### ISSUE THREAD

**Issue by zoeyTM** [NomicFoundation/hardhat-ignition#419]
Adding chalk to allow colours and font weights to be expressed.

For each log message consider the color/boldness choices.

**Comment by kanej** [comment]
Keep an eye out for any changes you would suggest for the simple UI.

**Comment by zoeyTM** [comment]
I'm not sure how feasible it is given the limitations of cross-compatibility between terminal systems, but it would be cool to synchronize color schemes between the simple-text-ui and the `visualize` ui as we update both.
