### ISSUE TITLE
Running against non-auto mining chain in first few blocks

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#516]
If you set a local hh node to non-automine, and try and run against it very early, you _sometimes_ see this error:

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/2b93de0f-c43f-45bc-af73-e5d3e7cff382)

I suspect the failure is in the issue is in our nonce syncing. We check for a confirmed count x blocks in the past, but what if that leads to a negative number? See:

https://github.com/NomicFoundation/hardhat-ignition/blob/98eeb89b746640f09500417673948936586553d1/packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts#L86

We never ask for a negative block number (add validation to the rpc count method). And in this case we should figure out whether we should just look back to the genesis block or whether custom logic is required.

## Reproduce steps

1. Go to sample examples
2. Set the hh config so the hardhat network doesn't automine and it has a 10s interval
3. Start a new node
4. Run an ignition deployment against the node immediately

**Comment by alcuadrado** [comment]
Oh, I added a TODO about this yesterday 😅
