### ISSUE TITLE
Improve no deployment error message in status

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#527]
If you run the status command with a non-existant deployment id you get:

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/9718cdd7-158f-48c8-973e-efdf54ce5689)

At the least the stack trace should be removed. Maybe a pattern to follow is HHs:

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/e5b002fc-11e8-4cad-91bd-9126a2c05b9a)

**Comment by alcuadrado** [comment]
Let's rethrow with a message that includes the ignition error code. The errors thrown should be `NomicFoundationHardhatPluginError`. This won't show any Hardhat error code, but it works for now. Then we will extend Hardhat so that the error-code system is extensible.
