### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat-ignition#583]
Some small improvements to the CLI that we should implement:

* If I rerun a deployment that is already complete, and doesn’t need any further action, the output shouldn’t be “successfully deployed”.
* We should let the users know when there's a gas bump

**Comment by kanej** [comment]
We should show actual spinners to indicate to the user that they should wait for execution to complete, rather than assume ignition has crashed because nothing updates.

**Comment by kanej** [comment]
Closing in preference to the epic #585
