### ISSUE TITLE
viem support

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#589]
Hardhat Ignition can be used in tests and scripts to deploy modules, the deploy function returns the contract instances as Ethers v6 contract objects. With the release of viem support in Hardhat, we should also support the option of returning viem contract objects.

We need to determine the build and release strategy to support a viem version of Ignition. We should also evaluate any other implications to viem usage with Ignition.

## TODO

- [x] #603
- [x] #616

**Comment by wighawag** [comment]
Just stumbled on this while looking at the open issues, and though might give some feedback :)


Why do you not make hardhat-ignition  agnostic  ?

hardhat-deploy let user use any lib they want. a deployment is basically a an artifact + address.

you can always add wrapper to make it more convenient. for hardhat-deploy, there is hardhat-deploy-ethers. you could follow a similar strategy

**Comment by kanej** [comment]
> Just stumbled on this while looking at the open issues, and though might give some feedback :)
> 
> Why do you not make hardhat-ignition agnostic ?
> 
> hardhat-deploy let user use any lib they want. a deployment is basically a an artifact + address.
> 
> you can always add wrapper to make it more convenient. for hardhat-deploy, there is hardhat-deploy-ethers. you could follow a similar strategy

I think this is the path we will go down. With a `hardhat-ignition` package that only provides cli support, and extension packages that you can opt into for ethers/viem support in tests and scripts.

**Comment by kanej** [comment]
Released as part of `v0.13.0`. We separated out `@nomicfoundation/hardhat-ignition` from `@nomicfoundation/hardhat-ignition-ethers`, and added `@nomicfoundation/hardhat-ignition-viem`.

See our Viem guide for more details: https://hardhat.org/ignition/docs/guides/viem
