### ISSUE TITLE
Deploying to Sepolia using Infura throws a dropped transaction error

### ISSUE THREAD

**Issue by zoeyTM** [NomicFoundation/hardhat-ignition#633]
For some reason, deploying to Sepolia network through Infura causes Ignition to throw a dropped transaction error, despite the transaction being successfully sent to the chain. This does not happen when deploying to Goerli through Infura, and it also doesn't happen when deploying to Sepolia through Alchemy. 

This appears to be a bug in Infura, but there may be a way for us to work around it or handle this niche case more gracefully. Needs more investigation.

Current workaround is to use Alchemy when deploying to Sepolia.

**Comment by kanej** [comment]
This may be because infura operates multiple memory pools.
We should retry in the presence of a dropped transaction incase we have read from the wrong mempool.

**Comment by gionn** [comment]
@zoeyTM any chance the error was the same of https://github.com/NomicFoundation/hardhat-ignition/issues/665?
