### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by egorFiNE** [NomicFoundation/hardhat-ignition#643]
Non-minor version 0.12.0 released with quite a few new features. I believe CHANGELOG.md or some sort of release notes would be beneficial for the community. Otherwise how do we know we can upgrade and not break things?

**Comment by kanej** [comment]
Hey @egorFiNE, this repo is a monorepo.

You can find the changelog under each of the individual packages. The main one is the `@nomicfoundation/hardhat-ignition` changelog, you can find at:

https://github.com/NomicFoundation/hardhat-ignition/blob/main/packages/hardhat-plugin/CHANGELOG.md

**Comment by egorFiNE** [comment]
@kanej indeed. Thank you very much!!
