### ISSUE TITLE
TypeError: `process.stdout.clearLine` is not a function

### ISSUE THREAD

**Issue by technophile-04** [NomicFoundation/hardhat-ignition#644]
### Description : 

Its seems `process.stdout.clearLine` might not work in some OS / node versions, recently encountered this error in our gh-actions CI job : 
https://github.com/scaffold-eth/scaffold-eth-2/actions/runs/7158553408/job/19490782791

https://github.com/NomicFoundation/hardhat-ignition/blob/4e06abfacc3638913d6698c9e429a4a393bb09c0/packages/hardhat-plugin/src/ui/pretty-event-handler.ts#L455

I think this was the cause in our case

### Similar issues reported on other repo's : 

https://forum.cloudron.io/topic/9219/calling-build-inside-a-docker-container

https://github.com/CookPete/auto-changelog/issues/73

https://github.com/hallh/elasticsearch-primary-balancer/issues/9

### Possible solution is to use `clearLine` from node's  [`readline`](https://nodejs.org/api/readline.html): 

```ts
import { clearLine } from 'readline'

clearLine(process.stdout, 0)
```

It was suggested here : https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions#comment80319576_34570694

**Comment by kanej** [comment]
Thanks @technophile-04, we will attempt to swap in the readline version of `clearLine`.
Either way we will get a fix in place to resolve running ignition within a github action.
