### ISSUE TITLE
Import path error

### ISSUE THREAD

**Issue by Confucian-e** [NomicFoundation/hardhat-ignition#662]
I have installed `@nomicfoundation/hardhat-ignition-ethers` but in module file should I still use `import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";` to import?
It shows an error `Module '"@nomicfoundation/hardhat-ignition-ethers"' has no exported member 'buildModule'.`
I think your doc not updated, so how to import correctly?

**Comment by kanej** [comment]
@Confucian-e, you are correct the import for `buildModule` is `import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";`

Where in our docs are we showing the `"@nomicfoundation/hardhat-ignition-ethers"` import? We will get it fixed.

**Comment by Confucian-e** [comment]
There is an error when I use `import { buildModule } from "@nomicfoundation/hardhat-ignition/modules` and my dependency installed is `@nomicfoundation/hardhat-ignition-ethers`, how to fix that?

**Comment by kanej** [comment]
@Confucian-e is the repo you are using open source so I can take a look.

If not can how are you importing Ignition in your hardhat config file? Are you requiring `"@nomicfoundation/hardhat-ignition-ethers"`?
