### ISSUE TITLE
Add task to fetch mapping of `<network name, deployment folder>`

### ISSUE THREAD

**Issue by SebastienGllmt** [NomicFoundation/hardhat-ignition#668]
# Goal

From an external plugin, leverage deployment information managed by `hardhat-ignition` (ex: `hardhat-interact` to interact with deployed contracts)

# Current state of things

From an external plugin, I can know which network the user wants to interact with if they run their command like this `npx hardhat --network localhost` since this information is available from `hre.network`

However, I get stuck here because there is no way to map from a network name (ex: `localhost`) to the folder `hardhat-ignition` uses for deployments.

## Attempt 1) Use the chain ID
It's tempting to think one could just check `network.config.chainId` and fallback to a `eth_chainId` RPC call, but this isn't sufficient because there is no guarantee the folder for `hardhat-ignition` is of the format `chain-XXX` because the `deploy` task takes an optional `deploymentId` that overrides the folder name

## Attempt 2) Use the `deployments` task

There is a task that gets all the deployments (#646). However, this just gives a list of folder names and doesn't say which network name these correspond to. 

# Solutions

## Option 1) Store the network name on disk

If the network name was stored somewhere on disk, apps could read all the deployments to build a mapping of `<name, deployment>` themselves.

This is not great since:
1. It's somewhat fragile (if `hardhat-ignition` changes the file format, this break downstream tools)
2. There is no guarantee it's up-to-date (if somebody changes their `hardhat.config.ts` but doesn't rerun `ignition deploy`, the app may read stale data)

## Option 2) Provide a task to get this information

Similar to #646, there could be a separate task (or an addition to the `deployments` task) that helps fetch the connection between network names and deployment folders.

I prefer this option. It also helps since it means plugins don't have to go parse the `ignition` path in the hardhat config (although asking plugins to just read `paths.ignition` from the hardhat config is not that bad)

## XY Problem concern

The [XY Problem](https://mywiki.wooledge.org/XyProblem) is when problem X causes Y and you ask for a solution for Y instead of X

I fear this issue may be somewhat of an XY problem, as the entire reason I made this is so that I can, from an external tool, go in and manually read the contents of `deployed_addresses.json` and the `artifacts` folder myself to parse the result of hardhat-ignition

If there was a better way for me to get all the `<address, ABI>` pairs for a given network name, then I wouldn't need anything mentioned in this issue (but I would still need to be able to query this mapping using the network name, so there is still a relation to the main issue)

**Comment by kanej** [comment]
Hey @SebastienGllmt, thanks for raising the issue.

Each deployment that is captured in the deployments folder is against a particular chain. We store that information within the journal, but I realise that parsing a line json log file for one piece of data is not ideal.

If we enhanced the deployments core function that underlies the deployments task to include the `chainId`, would that meet the requirement? So you could leverage the underlying Ignition core function for deployments and get the list of deployments, filter by `chainId` and then read the deployed addresses for each of those deployments with the `status` function.

**Comment by SebastienGllmt** [comment]
> I realise that parsing a line json log file for one piece of data is not ideal.

Yeah I guess you can use `eth_chainId`, then parse all journals to find the one that matches (a little ugly, but you're right that it should work)

> If we enhanced the deployments core function that underlies the deployments task to include the chainId, would that meet the requirement
Chain ID isn't necessarily enough because the folder name where the deployments are stored is not necessarily in the format `chain-XXX`. It would be better to instead get the folder name (otherwise you would have to parse all journals to find the folder that matches the chain ID)

**Comment by kanej** [comment]
The deployments function should list each deployment by `deploymentId`, which is used as the name of the folder when storing under the `./ignition/deployments` folder - we default to `chain-xxx` if the user doesn't provide a `deploymentId`.

Usage of the deployments function should give you a list of all deployments and for each deployment their deploymentId and potentially the `networkId`. We are adding a status function that will allow you to read the deployed addresses (and other data like abi) for a deployment based on `deploymentId`.
