### ISSUE TITLE
Document optional owner usage

### ISSUE THREAD

**Issue by SebastienGllmt** [NomicFoundation/hardhat-ignition#673]
Many contracts take the owner as an input parameter. I want to be able to set the owner of these contracts dynamically, but fallback to the HardHat account.

## Current state

For a lot of these contracts, I would like to do something like this:

```typescript
const owner = m.getParameter<string>('owner', m.getAccount(0))
```

However, this isn't possible because the types are different (`string` and `AccountRuntimeValue` are not comparable, and there is no way to convert between the two types)

## Alternatives

Other than adding a way to convert between these types, another way to tackle this would be to instead encourage people to use indices instead of owners

i.e something like this:

```ts
const ownerIndex = m.getParameter<number>('ownerIndex', 0);
m.getAccount(ownerIndex );
```

This code won't work (for the same reason as above), but it could be that implementing conversion between numbers like this is easier than converting between accounts

**Comment by kanej** [comment]
I agree that for the use case, using the return result of `getAccount` works better:

```const owner = m.getParameter<string>('owner', m.getAccount(0))```

If your thinking in terms of setting the owner, then having to work through the intermediary accounts concept is a friction.
