### ISSUE TITLE
add --no-confirm flag for integrations with external tools

### ISSUE THREAD

**Issue by TheSnakeWitcher** [NomicFoundation/hardhat-ignition#677]
Hi, I am developing a neovim plugin for hardhat integration, currently when I trying to deploy a contract from the plugin using `hardhat-ignition` the confirmation requests just stop the process. I think that is a good measure to ask these confirmation to avoid errors but it will complicate things for integrations with other tools. I personally think that to add `--noconfirm` flag could be a good approach. Thanks in advanced.

**Comment by zoeyTM** [comment]
HI @TheSnakeWitcher, thanks for opening the issue! 

I agree this is a needed feature, and have actually already added it in the form of environment variables that let you skip the confirmation altogether (similar to the way Hardhat also does this). The work can be found in https://github.com/NomicFoundation/hardhat-ignition/pull/653 (though it's not the focal point of the PR).
