### ISSUE TITLE
Toolbox: Investigate assert.isDefined issue

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#688]
Investigate the test issue with chai assert in the HH toolbox PR, see comment https://github.com/NomicFoundation/hardhat/pull/4655#discussion_r1476274226

**Comment by zoeyTM** [comment]
This was not reproducible for me. I added back the `assert.isDefined(this.env);` line and the test passed without issue.

**Comment by kanej** [comment]
We resolved this by bumping the version of `chai`.
