### ISSUE TITLE
blocktime

### ISSUE THREAD

**Issue by sambP** [NomicFoundation/hardhat-ignition#695]
I have to call some contract functions with a deadline in my deployment. For that the current blocktime is required. First of all, is there any smart solution to access that?

I added a hacky view function to one of my contracts for receiving it as a static future. That works, but now I have to add some seconds so the deadline isn't rejected. That doesn't work (of course). 

So my question: How do I get access to the current blocktime and be able to add some seconds to that number?

**Comment by kanej** [comment]
The Module API doesn't currently provide a way to add arbitrary JS manipulation of the result value of a static call.

You do have the option of running Ignition programmatically and [passing a parameter](https://hardhat.org/ignition/docs/guides/tests#using-module-parameters) for the deadline, so writing a Hardhat script that reads the blocktime and incrementing it then invoking something like:

```ts
const deadline = await calculateDeadline();

const result = await hre.ignition.deploy(MyModule, {
  parameters: {
      MyModule: {
        deadline
      },
    },
});
```

**Comment by sambP** [comment]
Alright, got the concept. Thanks.
