### ISSUE TITLE
Deploying a contract via script with '--network localhost' should create the 'deployments' folder

### ISSUE THREAD

**Issue by ChristopherDedominici** [NomicFoundation/hardhat-ignition#703]
In a HH project, if I run the CLI command:

```
npx hardhat ignition deploy ./ignition/modules/Token.js --network localhost
```
the folder 'deployments' is created inside the folder 'ignition'.

But, if in a JS script (e.g.: scripts/deploy.js), I add the following deployment code

```
const { token } = await ignition.deploy(TokenModule);
```
and then I run

```
npx hardhat run scripts/deploy.js --network localhost
```

the folder 'deployments' is not created.
I would expect this behavior to be correct if I was not specifying a persistent network (not including '--network localhost'), e.g.:

```
npx hardhat run scripts/deploy.js
```

but in persistent networks I would expect to see the 'deployments' folder being created.

**Comment by kanej** [comment]
That `hre.ignition.deploy` method should allow setting the deployment id.

Currently this is being controlled through the deployment directory on the constructor but that doesn't allow the user in a script to create a specific deploy or to leverage an existing deploy.
