### ISSUE TITLE
Add ignition/deployment to gitignore

### ISSUE THREAD

**Issue by tnakagawa** [NomicFoundation/hardhat-ignition#719]
I don't think you need to commit ignition/deployment to Github.

At the very least, I think localhost (chain-31337) is unnecessary.

I think you should add some folders that do not require commits added by the ignition function to the "packages/hardhat-core/recommended-gitignore.txt" file.

note
Since my native language is not English, I will use Google Translate to translate it.
Sorry if there are any inappropriate expressions.

**Comment by kanej** [comment]
We wanted to encourage devs to be explicit in excluding the deployments folder - as it means that a deployment can't be resumed/metadata like deployed addresses be retreived.

However ignoring the default localhost folder `chain-31337` is a great point.

**Comment by kanej** [comment]
We should update the Hardhat sample projects to ignore `./ignition/deployments/chain-31337` by default.
If you are commiting the deployment metadata and journal information for those, that is unexpected.
