### ISSUE TITLE
Dealing with circular dependencies

### ISSUE THREAD

**Issue by martelskiy** [NomicFoundation/hardhat-ignition#732]
Hi,
I apologize if this topic has already been covered, though I could not find any information on it. 
I need to deploy multiple contracts with circular dependencies. It's important to note that these circular dependencies occur during function execution after deployment(not in constructors of course). Ideally, I would like to use the Hardhat Ignition feature to initialize contracts as part of the module's execution

Example:
```solidity
contract Foo {
    address bar;
    function initialize(address bar_) external {
        bar = bar_;
    }
}
```
```solidity
contract Bar {
    address foo;
    function initialize(address foo_) external {
        foo = foo_;
    }
}
```

which results in this error:
`IgnitionError: IGN1: Internal Hardhat Ignition invariant was violated: Trying to use `undefined` as submodule. Make sure you don't have a circular dependency of modules`

I think it is tolerable Ignition's inability to handle this. However, I would then expect the library to provide me with the capability to fetch the deployed contract addresses, so I can develop custom multi-stage scripts—for example, deployment via Ignition and semi-manual initialization afterward.
Overall, my feeling, at this point in time, is that Ignition lacks flexibility and documentation when there is something custom needed.

Other questions are:
- Is there a way to fetch values from the parameters JSON file programmatically? In case the engineer wants to alter the values based on some conditions, etc?
- Is there a way to execute Ignition modules programmatically (not from the **CLI**)? Example use case: I've got 135 modules and I do not want to run 135 commands manually. Today I would need to create a bash script to do that which adds complexity, the better way could be something like this:
```typescript
import { ignition } from "hardhat";

function main() {
  const { moduleNames } = ignition.GetModules();

  moduleNames.forEach((name) => {
    ignition.ExecuteModule(name);
  });
}
```

**Comment by kanej** [comment]
Hey @martelskiy thanks for the feedback.

I would have expected a module something like the following would cover your contracts depending on each other case:

```ts
const myModule = buildModule("MyModule", (m) => {
  const foo = m.contract("Foo");
  const bar = m.contract("Bar");

  m.call(foo, "initialize", [bar]);
  m.call(bar, "initialize", [foo]);
});

```

You can use Ignition in standard Hardhat scripts:

```ts
import { ignition } from "hardhat";

function main() {
  const myModule = require("./ignition/modules/myModule.js")

  ignition.deploy(myModule);
}
```

I realise the dynamic require is funky. You could invoke the `deploy` task programmatically from within a hardhat script passing the path to the Ignition module file.

We are unlikely to enhance `hre.ignition.deploy(...)` to take a module name rather than a constructed module object. However that is not to say we cannot alternate helper methods that are more aware of the modules folder.

Is the use case here really "deploy all module files under `./ignition/modules`"?

**Comment by kanej** [comment]
`deploy` takes an options object as the second argument. One of the properties is `parameters` which is keyed by `module-id` then the parameter itself:

```js
it("should allow setting the start count for new counters", async function () {
  const { counter } = await ignition.deploy(CounterModule, {
    parameters: {
      Counter: {
        startCount: 42,
      },
    },
  });

  assert.equal(await counter.count(), 42);
});
```

In the example above the module id is `Counter`, so the string passed in to `buildModule` to name the module.

https://hardhat.org/ignition/docs/guides/tests#using-module-parameters
