### ISSUE TITLE
Handling of case insensitive parameters could be improved

### ISSUE THREAD

**Issue by mwawrusch** [NomicFoundation/hardhat-ignition#745]
I just ran into this issue:

I deployed a module via command line, then included it in a script and redployed the module again. I received a reconciliation error because of an argument has been changed. Turns out that I passed an address to a function call
```
  m.call(ROJIVerseAccessManager,"initialize",  [[deployerAddress, primaryOwnerAddress]])
```

and the address differed slightly in casing (an e in the middle, to be exact).

This seems to be a bit too strict as that argument is converted into an address for the evm and thus is case insensitive.

**Comment by kanej** [comment]
I think that makes sense. We always want to display addresses we have received from the chain in checksum format, user input should not be forced to be in checksum format.

We should update the address reconciliation to be case insensitive. A quick look suggests updating this comparison to be a case insensitive comparison:

https://github.com/NomicFoundation/hardhat-ignition/blob/e6a5d85b4ef21c1b7a5e2dcbd3f68dd7c9bcec28/packages/core/src/internal/reconciliation/helpers/reconcile-address.ts#L26
