### ISSUE TITLE
Question:  How do I set maxFeePerGasLimit and maxFeePerGas?

### ISSUE THREAD

**Issue by bitcoinbrisbane** [NomicFoundation/hardhat-ignition#753]
Im trying to set the [maxFeePerGasLimit and maxFeePerGas](https://github.com/NomicFoundation/hardhat-ignition/blob/development/packages/core/src/deploy.ts#L54) values on the provider.   Looking through the code, it seems other config options can be added via a json file, with the Module.config.json file name. 

https://github.com/NomicFoundation/hardhat-ignition/blob/development/packages/hardhat-plugin/src/index.ts#L83-L85

Which gets passed to the deploy function here:  https://github.com/NomicFoundation/hardhat-ignition/blob/development/packages/hardhat-plugin/src/index.ts#L309

I see issue `maxFeePerGas` in core change log https://github.com/NomicFoundation/hardhat-ignition/issues/728 and in this PR https://github.com/NomicFoundation/hardhat-ignition/pull/740/files#diff-cf751dc54884bf798c9db3646b20d47265b9f794ff918a4e6b5bda17fa5e6717R42-R55

Or I cant seem to set both in the hardhat.config.ts file.  It doesnt like `maxPriorityFeePerGas` although this example shows it should https://github.com/NomicFoundation/hardhat-ignition/pull/740/files#diff-e9f931e8188cedfc1a6b71077cff47bc948c4b7e1a61a4a3e2c99dc0c478af13R9-R12

Any examples on how to do this?

### hardhat.config.ts
```
        immutableZkevmTestnet: {
            url: "https://rpc.testnet.immutable.com",
            accounts: ["x"],
            ignition: {
                maxFeePerGasLimit: BigInt(500000000000),
                maxPriorityFeePerGas: BigInt(50000000000),
            }
        }
```

### Eg config
```json
{
    "maxFeePerGasLimit": "50000000000",
    "maxFeePerGas": "50000000000"
}
```

VS code eg

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/8411406/4228e592-33d0-4d90-a450-af165cba4013)

**Comment by kanej** [comment]
Hey @bitcoinbrisbane, support for `maxPriorityFeePerGas` was introduced with the `v0.15.2` release, can you confirm you have that version installed?

You should be able to set both those values under the individual network configurations:

```ts
// hardhat.config.js
module.exports = {
  networks: {
    sepolia: {
      // ...
      ignition: {
        maxFeePerGasLimit: 50_000_000_000n, // 50 gwei
        maxPriorityFeePerGas: 2_000_000_000n, // 2 gwei
      },
      // ...
    },
  },
};
```

These is a config section in the docs:
https://hardhat.org/ignition/docs/config#network-configuration-options

**Comment by bitcoinbrisbane** [comment]
Good spot.  I was on 15.1.   This is my package.json now and seems to work!  Happy to close this issue.

```json
		"@nomicfoundation/hardhat-ethers": "^3.0.0",
		"@nomicfoundation/hardhat-ignition": "^0.15.2",
		"@nomicfoundation/hardhat-ignition-ethers": "^0.15.2",
		"@nomicfoundation/hardhat-network-helpers": "^1.0.10",
		"@nomicfoundation/hardhat-toolbox": "^5.0.0",
		"@nomicfoundation/hardhat-verify": "^2.0.6",
		"@nomicfoundation/ignition-core": "^0.15.1",
```
