### ISSUE TITLE
`RangeError: Maximum call stack size exceeded` during verification on deployment

### ISSUE THREAD

**Issue by doerfli** [NomicFoundation/hardhat-ignition#770]
### What happened?

Repo: https://github.com/etherisc/gif-next/
Branch: [experiment/ignition](https://github.com/etherisc/gif-next/tree/experiment/ignition) (make sure to use branch `experiment/ignition` as ignition only exists there)

During verification of ignition module `GifCore` an unexpected error is thrown (see below). The last contract to be successfully verified is `Libraries#TimestampLib`, so i assume the issue is with verification of contract `Libraries#StakeManagerLib`, but i am not entirely sure about that.

```
An unexpected error occurred:

RangeError: Maximum call stack size exceeded
    at /workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:30
    at Array.flatMap (<anonymous>)
    at getImportSourceNames (/workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:22)
    at /workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:37
    at Array.flatMap (<anonymous>)
    at getImportSourceNames (/workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:22)
    at /workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:37
    at Array.flatMap (<anonymous>)
    at getImportSourceNames (/workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:22)
    at /workspaces/gif-next/node_modules/@nomicfoundation/ignition-core/src/verify.ts:112:37
```

### Minimal reproduction steps

Deployment to polygon amoy using 

`npx hardhat ignition deploy ignition/modules/GifCore.ts --network polygonAmoy --verify` 

or manual verification using 

`npx hardhat ignition verify chain-80002 --network polygonAmoy` 

the error happens in both cases. Might happen on other chains too, but cannot test as i don't have tokens and setup for another chain where verification works. 

### Search terms

RangeError Maximum call stack size exceeded

**Comment by kanej** [comment]
We would need to dig deeper, but is it possible you have a circular dependency in your `import` statements?

**Comment by doerfli** [comment]
I don't think so. I am assuming that the solidity compiler does not allow circular dependencies. We had issues with the compiler throwing exceptions due to circular dependencies, but they're all removed. 
We can compile the code using hardhat (solc) as well as forge and also solhint does not complain. Deployment also works. I would expect that at least some of these steps complain if there is a circular dependency. 

Do you know of any form of circular dependency that the solc compiler accepts but ignition verify fails upon encountering? 

Our solidity contracts are quite extensive and a few of them are large and have a lot of inheritance. Could this be related to the stack too deep issue?

**Comment by kanej** [comment]
I don't think it is related to inheritance, I suspect our best avenue of investigation is a bug in Ignition's verify, particularly in its recursive reading of dependencies, and somehow that is getting in a loop.

We will do some debugging on your branch and get back.

**Comment by doerfli** [comment]
Ok. Thanks. 
Can i support the debugging in anyway? Can i provide some additional data or would it maybe help to have an interactive debug session?
