### ISSUE TITLE
@nomicfoundation/hardhat-ignition/modules not found when using Viem

### ISSUE THREAD

**Issue by Burtonium** [NomicFoundation/hardhat-ignition#795]
### What happened?

So why after `pnpm install --save-dev @nomicfoundation/hardhat-ignition-viem` do I get a `Module not found` after the following:

    import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

It doesnt explicitly state anywhere to install `@nomicfoundation/hardhat-ignition`, do I have to?

### Minimal reproduction steps

 Reproduction repo
 https://github.com/Burtonium/hardhat-ignition-viem-reproduction-repo

**Comment by kanej** [comment]
I did a install based on that repo in codespaces and was able to deploy without the `Module not found` error:

![image](https://github.com/user-attachments/assets/653a5859-9afd-4ab1-8239-2cdde60e00b0)

Note 1: I had to update some of the versions to meet peer deps (marked in red).
Note 2: The viem toolbox includes `@nomicfoundation/hardhat-ignition-viem`, so this can be dropped as a devDependency. 

I would clear your `node_modules` and try a fresh install.

**Comment by Burtonium** [comment]
I updated the reproduction repo, still the same on the latest version of VsCode.

**Comment by Burtonium** [comment]
I've confirmed that the issue happens with `yarn` or `pnpm` but not `npm`.

**Comment by kanej** [comment]
`yarn` and `pnpm` don't install peer dependencies by default.
If you are installing with `yarn` you need:

```shell
yarn add --dev @nomicfoundation/hardhat-ignition-ethers @nomicfoundation/hardhat-ethers @nomicfoundation/hardhat-ignition @nomicfoundation/hardhat-verify @nomicfoundation/ignition-core ethers
```

See: https://hardhat.org/ignition/docs/getting-started#installation, and switch the install instructions to `yarn`:

![image](https://github.com/user-attachments/assets/27b1d029-2013-41df-aaf9-04ba04940312)
