### ISSUE TITLE
Error HH303: Unrecognized task 'ignition'... Kkeep getting this when I try to deploy my contract

### ISSUE THREAD

**Issue by akorede12** [NomicFoundation/hardhat-ignition#802]
### What happened?

My contract is a ecommerce contract that imports a couple of open-zeppelin contracts and some local contracts and a library

I keep getting this "Error HH303: Unrecognized task 'ignition'" when i try to use ignition to deploy the contract. 

Do keep in mind I'm on windows 10 with the latest version of hardhat

### Minimal reproduction steps

Error HH303: Unrecognized task 'ignition'

 "devDependencies": {
    "@nomicfoundation/hardhat-ignition-ethers": "^0.15.5",
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.10"
  },
  "dependencies": {
    "@nomicfoundation/hardhat-ignition": "^0.15.5",
    "@openzeppelin/contracts": "^5.0.2",
    "dotenv": "^16.4.5",
    "ten-hardhat-plugin": "^0.0.11"
  }

ignition script
module.exports = buildModule("ShoppyModule", (m) => {
  const deployer = m.getAccount(0);
  const apollo = m.contract("ShoppieSales", {
    from: deployer,
  });

  return { apollo };
});

module.exports = ShoppyModule;

### Search terms

hh303

**Comment by zoeyTM** [comment]
@akorede12 Can you show us the contents of your Hardhat config file? I suspect you may have forgotten to import/require `hardhat-ignition-ethers`.

**Comment by zoeyTM** [comment]
Closing this as I'm pretty sure it's just an import issue. If the author comes back and updates the issue to indicate otherwise then we can reopen.
