### ISSUE TITLE
Better options for "Deployment flow" visualization

### ISSUE THREAD

**Issue by tmigone** [NomicFoundation/hardhat-ignition#806]
### Describe the feature

When there is a lot of stuff going on the `Deployment flow` diagram gets very hard to view. Not sure what control options mermaid allows (or even if this is mermaid based?), but some form of zoom perhaps would help here?

<img width="1357" alt="Screenshot 2024-09-11 at 5 54 20 PM" src="https://github.com/user-attachments/assets/5397811c-2fda-4c7a-b90b-495ffbee8231">

**Comment by alcuadrado** [comment]
I think we can use this to give a google-maps-like zoom experience https://github.com/mermaid-js/mermaid/issues/2162#issuecomment-1542542439

**Comment by tmigone** [comment]
That would be nice!
