### ISSUE TITLE
Deployment verification looking for dbg.json files

### ISSUE THREAD

**Issue by tmigone** [NomicFoundation/hardhat-ignition#817]
### What happened?

Trying to verify contracts on etherscan and it's erroring out, trying to access some dbg.json files which don't exist.

```
✗ npx hardhat ignition verify chain-421614
WARNING: You are currently using Node.js v22.6.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions


An unexpected error occurred:

[Error: ENOENT: no such file or directory, open '/Users/tomi/git/thegraph/contracts/packages/horizon/ignition/deployments/chain-421614/artifacts/BridgeEscrow#BridgeEscrow.dbg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tomi/git/thegraph/contracts/packages/horizon/ignition/deployments/chain-421614/artifacts/BridgeEscrow#BridgeEscrow.dbg.json'
}
```

### Minimal reproduction steps

1. Deploy modules: https://github.com/graphprotocol/contracts/pull/1025
2. Run `npx hardhat ignition verify chain-421614`

### Search terms

verify, ignition

**Comment by kanej** [comment]
I am going to close this in preference for https://github.com/NomicFoundation/hardhat-ignition/issues/823
