### ISSUE TITLE
Deploy UUPS upgradable proxies using hardhat ignition and ethers upgrades library

### ISSUE THREAD

**Issue by joa2040** [NomicFoundation/hardhat-ignition#820]
### Describe the feature

Using a hardhat task, I can deploy UUPS proxies using @openzeppelin/hardhat-upgrades like this:

```
    const MyContract = await hre.ethers.getContractFactory('MyContract');
    const myContract = await hre.upgrades.deployProxy(MyContract, [arg1, arg2]);
    await myContract.waitForDeployment();

    const myContractAddress = await myContract.getAddress();
    console.log(`MyContract Proxy address: ${myContractAddress}`);
```

Is there any chance to do the same using ignition? I would like to combine this with ignition in order to use create2 feature

### Search terms

hardhat ignition uups upgradeable

**Comment by kanej** [comment]
Hey, we have a tutorial walking through upgradable contracts that uses the older `TransparentUpgradeableProxy` pattern: https://hardhat.org/ignition/docs/guides/upgradeable-proxies

There is a [related issue](https://github.com/NomicFoundation/hardhat-ignition/issues/788) requesting documentation into how to use the existing Ignition API for the UUPS pattern, some of the discussion might be useful: https://github.com/NomicFoundation/hardhat-ignition/issues/788

We want Ignition to better support upgradable contracts. There is design work to be done around extending the existing API to allow these patterns to be expressed succinctly, while also not painting Ignition into a corner as upgrade techniques change.

**Comment by joa2040** [comment]
Hi @kanej! thanks for your prompt response

I saw that tutorial but I cannot use safe upgrades there.
I will be waiting for those ignition updated! Will close this issue for now

**Comment by joa2040** [comment]
Closed

**Comment by joa2040** [comment]
Close
